// Code generated by go-bindata.
// sources:
// ui/build/asset-manifest.json
// ui/build/favicon.ico
// ui/build/index.html
// ui/build/manifest.json
// ui/build/service-worker.js
// ui/build/static/css/main.c2c9a1d0.css
// ui/build/static/css/main.c2c9a1d0.css.map
// ui/build/static/js/main.396dcec5.js
// ui/build/static/js/main.396dcec5.js.map
// ui/build/static/media/glyphicons-halflings-regular.448c34a5.woff2
// ui/build/static/media/glyphicons-halflings-regular.89889688.svg
// ui/build/static/media/glyphicons-halflings-regular.e18bbf61.ttf
// ui/build/static/media/glyphicons-halflings-regular.f4769f9b.eot
// ui/build/static/media/glyphicons-halflings-regular.fa277232.woff
// ui/build/static/media/logo.5d5d9eef.svg
// DO NOT EDIT!

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// assetManifestJson reads file data from disk. It returns an error on failure.
func assetManifestJson() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/asset-manifest.json"
	name := "asset-manifest.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// faviconIco reads file data from disk. It returns an error on failure.
func faviconIco() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/favicon.ico"
	name := "favicon.ico"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// indexHtml reads file data from disk. It returns an error on failure.
func indexHtml() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/index.html"
	name := "index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// manifestJson reads file data from disk. It returns an error on failure.
func manifestJson() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/manifest.json"
	name := "manifest.json"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// serviceWorkerJs reads file data from disk. It returns an error on failure.
func serviceWorkerJs() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/service-worker.js"
	name := "service-worker.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticCssMainC2c9a1d0Css reads file data from disk. It returns an error on failure.
func staticCssMainC2c9a1d0Css() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/css/main.c2c9a1d0.css"
	name := "static/css/main.c2c9a1d0.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticCssMainC2c9a1d0CssMap reads file data from disk. It returns an error on failure.
func staticCssMainC2c9a1d0CssMap() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/css/main.c2c9a1d0.css.map"
	name := "static/css/main.c2c9a1d0.css.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsMain396dcec5Js reads file data from disk. It returns an error on failure.
func staticJsMain396dcec5Js() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/js/main.396dcec5.js"
	name := "static/js/main.396dcec5.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticJsMain396dcec5JsMap reads file data from disk. It returns an error on failure.
func staticJsMain396dcec5JsMap() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/js/main.396dcec5.js.map"
	name := "static/js/main.396dcec5.js.map"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticMediaGlyphiconsHalflingsRegular448c34a5Woff2 reads file data from disk. It returns an error on failure.
func staticMediaGlyphiconsHalflingsRegular448c34a5Woff2() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/media/glyphicons-halflings-regular.448c34a5.woff2"
	name := "static/media/glyphicons-halflings-regular.448c34a5.woff2"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticMediaGlyphiconsHalflingsRegular89889688Svg reads file data from disk. It returns an error on failure.
func staticMediaGlyphiconsHalflingsRegular89889688Svg() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/media/glyphicons-halflings-regular.89889688.svg"
	name := "static/media/glyphicons-halflings-regular.89889688.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticMediaGlyphiconsHalflingsRegularE18bbf61Ttf reads file data from disk. It returns an error on failure.
func staticMediaGlyphiconsHalflingsRegularE18bbf61Ttf() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/media/glyphicons-halflings-regular.e18bbf61.ttf"
	name := "static/media/glyphicons-halflings-regular.e18bbf61.ttf"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticMediaGlyphiconsHalflingsRegularF4769f9bEot reads file data from disk. It returns an error on failure.
func staticMediaGlyphiconsHalflingsRegularF4769f9bEot() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/media/glyphicons-halflings-regular.f4769f9b.eot"
	name := "static/media/glyphicons-halflings-regular.f4769f9b.eot"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticMediaGlyphiconsHalflingsRegularFa277232Woff reads file data from disk. It returns an error on failure.
func staticMediaGlyphiconsHalflingsRegularFa277232Woff() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/media/glyphicons-halflings-regular.fa277232.woff"
	name := "static/media/glyphicons-halflings-regular.fa277232.woff"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// staticMediaLogo5d5d9eefSvg reads file data from disk. It returns an error on failure.
func staticMediaLogo5d5d9eefSvg() (*asset, error) {
	path := "/Users/sebastian/Projects/go/src/github.com/shimberger/gohls/ui/build/static/media/logo.5d5d9eef.svg"
	name := "static/media/logo.5d5d9eef.svg"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"asset-manifest.json": assetManifestJson,
	"favicon.ico": faviconIco,
	"index.html": indexHtml,
	"manifest.json": manifestJson,
	"service-worker.js": serviceWorkerJs,
	"static/css/main.c2c9a1d0.css": staticCssMainC2c9a1d0Css,
	"static/css/main.c2c9a1d0.css.map": staticCssMainC2c9a1d0CssMap,
	"static/js/main.396dcec5.js": staticJsMain396dcec5Js,
	"static/js/main.396dcec5.js.map": staticJsMain396dcec5JsMap,
	"static/media/glyphicons-halflings-regular.448c34a5.woff2": staticMediaGlyphiconsHalflingsRegular448c34a5Woff2,
	"static/media/glyphicons-halflings-regular.89889688.svg": staticMediaGlyphiconsHalflingsRegular89889688Svg,
	"static/media/glyphicons-halflings-regular.e18bbf61.ttf": staticMediaGlyphiconsHalflingsRegularE18bbf61Ttf,
	"static/media/glyphicons-halflings-regular.f4769f9b.eot": staticMediaGlyphiconsHalflingsRegularF4769f9bEot,
	"static/media/glyphicons-halflings-regular.fa277232.woff": staticMediaGlyphiconsHalflingsRegularFa277232Woff,
	"static/media/logo.5d5d9eef.svg": staticMediaLogo5d5d9eefSvg,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"asset-manifest.json": &bintree{assetManifestJson, map[string]*bintree{}},
	"favicon.ico": &bintree{faviconIco, map[string]*bintree{}},
	"index.html": &bintree{indexHtml, map[string]*bintree{}},
	"manifest.json": &bintree{manifestJson, map[string]*bintree{}},
	"service-worker.js": &bintree{serviceWorkerJs, map[string]*bintree{}},
	"static": &bintree{nil, map[string]*bintree{
		"css": &bintree{nil, map[string]*bintree{
			"main.c2c9a1d0.css": &bintree{staticCssMainC2c9a1d0Css, map[string]*bintree{}},
			"main.c2c9a1d0.css.map": &bintree{staticCssMainC2c9a1d0CssMap, map[string]*bintree{}},
		}},
		"js": &bintree{nil, map[string]*bintree{
			"main.396dcec5.js": &bintree{staticJsMain396dcec5Js, map[string]*bintree{}},
			"main.396dcec5.js.map": &bintree{staticJsMain396dcec5JsMap, map[string]*bintree{}},
		}},
		"media": &bintree{nil, map[string]*bintree{
			"glyphicons-halflings-regular.448c34a5.woff2": &bintree{staticMediaGlyphiconsHalflingsRegular448c34a5Woff2, map[string]*bintree{}},
			"glyphicons-halflings-regular.89889688.svg": &bintree{staticMediaGlyphiconsHalflingsRegular89889688Svg, map[string]*bintree{}},
			"glyphicons-halflings-regular.e18bbf61.ttf": &bintree{staticMediaGlyphiconsHalflingsRegularE18bbf61Ttf, map[string]*bintree{}},
			"glyphicons-halflings-regular.f4769f9b.eot": &bintree{staticMediaGlyphiconsHalflingsRegularF4769f9bEot, map[string]*bintree{}},
			"glyphicons-halflings-regular.fa277232.woff": &bintree{staticMediaGlyphiconsHalflingsRegularFa277232Woff, map[string]*bintree{}},
			"logo.5d5d9eef.svg": &bintree{staticMediaLogo5d5d9eefSvg, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

